# Generated by Django 4.1.3 on 2022-12-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_new_user_user_extends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Extends',
        ),
        migrations.AddField(
            model_name='registeruser',
            name='text_messenger',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
