# Generated by Django 4.1.3 on 2022-12-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_delete_user_extends_registeruser_text_messenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeruser',
            name='name_friend',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
